apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: qeventingservice
  name: qeventingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qeventingservice
  template:
    metadata:
      labels:
        app: qeventingservice
    spec:
      containers:
      - name: qeventingservice
        image: dev.local/burrsutter/qeventingservice:1.0.0
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "40Mi" 
            cpu: "100m" 
          limits:
            memory: "40Mi"
            cpu: "100m" 
        livenessProbe:
          httpGet:
              port: 8080
              path: /healthz
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2          
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3
