apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: event-cronjob-source
spec:
  schedule: "* * * * *"
  data: '{"message": "Every Minute"}'
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: qeventingservice
