apiVersion: v1
kind: Service
metadata:
  name: qeventingservice
  labels:
    app: qeventingservice    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: qeventingservice
  type: LoadBalancer