apiVersion: v1
kind: PersistentVolume
metadata:
  name: ms-sql-pv
  labels:
    type: local
spec:
  storageClassName: mystorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/data/mssqldata/"
